name: PageSpeed Insights Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pagespeed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run PageSpeed Insights
        uses: JakePartusch/psi-action@v1.3
        with:
          url: 'https://andrieu-pierre.surge.sh/'
          strategy: 'desktop'
          key: ${{ secrets.PAGESPEED_API_KEY }}
